# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DIAN-Pilot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DIAN-Pilot

  target 'DIAN-PilotTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DIAN-PilotUITests' do
    inherit! :search_paths
    # Pods for testing
  end
	source 'https://github.com/CocoaPods/Specs.git'
	pod 'Zip', '~> 0.6'
end
